
create table if not exists public.admin_emails (
  email text primary key
);


insert into public.admin_emails (email)
values ('tenka.sdv@gmail.com')
on conflict (email) do nothing;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_emails ae
    where ae.email = auth.email()
  );
$$;

grant execute on function public.is_admin() to authenticated;

create table if not exists public.kotoba_entries (
  id bigint generated by default as identity primary key,
  tier text not null default 'N4',
  chapter integer not null default 1,
  sub_tier integer not null default 1,
  kana text not null,
  romaji text not null,
  meaning_en text not null,
  meaning_id text not null,
  example text not null default '',
  segments jsonb not null default '[]'::jsonb,
  example_translation_en text not null default '',
  example_translation_id text not null default '',
  kanji_word text not null default '',
  kanji_example text not null default '',
  usage_en text,
  usage_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.kanji_entries (
  id bigint generated by default as identity primary key,
  tier text not null default 'N4',
  chapter integer not null default 1,
  sub_tier integer not null default 1,
  kanji text not null,
  reading text not null,
  meaning_en text not null,
  meaning_id text not null,
  kana text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.bunpo_entries (
  id bigint generated by default as identity primary key,
  tier text not null default 'N4',
  chapter integer not null default 1,
  sub_tier integer not null default 1,
  pattern text not null,
  example text not null,
  meaning_en text not null,
  meaning_id text not null,
  segments jsonb not null default '[]'::jsonb,
  blank_version text not null default '',
  example_translation_en text not null default '',
  example_translation_id text not null default '',
  usage_note_en text,
  usage_note_id text,
  created_at timestamptz not null default now()
);

create index if not exists kotoba_entries_tier_idx on public.kotoba_entries (tier);
create index if not exists kanji_entries_tier_idx on public.kanji_entries (tier);
create index if not exists bunpo_entries_tier_idx on public.bunpo_entries (tier);

alter table public.kotoba_entries enable row level security;
alter table public.kanji_entries enable row level security;
alter table public.bunpo_entries enable row level security;

drop policy if exists "public read kotoba" on public.kotoba_entries;
create policy "public read kotoba" on public.kotoba_entries
  for select using (true);

drop policy if exists "admin write kotoba insert" on public.kotoba_entries;
create policy "admin write kotoba insert" on public.kotoba_entries
  for insert to authenticated with check (public.is_admin());

drop policy if exists "admin write kotoba update" on public.kotoba_entries;
create policy "admin write kotoba update" on public.kotoba_entries
  for update to authenticated using (public.is_admin());

drop policy if exists "admin write kotoba delete" on public.kotoba_entries;
create policy "admin write kotoba delete" on public.kotoba_entries
  for delete to authenticated using (public.is_admin());

drop policy if exists "public read kanji" on public.kanji_entries;
create policy "public read kanji" on public.kanji_entries
  for select using (true);

drop policy if exists "admin write kanji insert" on public.kanji_entries;
create policy "admin write kanji insert" on public.kanji_entries
  for insert to authenticated with check (public.is_admin());

drop policy if exists "admin write kanji update" on public.kanji_entries;
create policy "admin write kanji update" on public.kanji_entries
  for update to authenticated using (public.is_admin());

drop policy if exists "admin write kanji delete" on public.kanji_entries;
create policy "admin write kanji delete" on public.kanji_entries
  for delete to authenticated using (public.is_admin());

drop policy if exists "public read bunpo" on public.bunpo_entries;
create policy "public read bunpo" on public.bunpo_entries
  for select using (true);

drop policy if exists "admin write bunpo insert" on public.bunpo_entries;
create policy "admin write bunpo insert" on public.bunpo_entries
  for insert to authenticated with check (public.is_admin());

drop policy if exists "admin write bunpo update" on public.bunpo_entries;
create policy "admin write bunpo update" on public.bunpo_entries
  for update to authenticated using (public.is_admin());

drop policy if exists "admin write bunpo delete" on public.bunpo_entries;
create policy "admin write bunpo delete" on public.bunpo_entries
  for delete to authenticated using (public.is_admin());

-- Nama per (tier, chapter, sub_tier), misal "Tier 1.1 — Personal Pronouns &
-- Greetings". Dipisah dari kotoba/kanji/bunpo_entries karena satu chapter.sub_tier
-- dipakai bareng oleh banyak entry — nama-nya cukup disimpan sekali.
create table if not exists public.section_titles (
  tier text not null,
  chapter integer not null,
  sub_tier integer not null,
  title_en text not null default '',
  title_id text not null default '',
  primary key (tier, chapter, sub_tier)
);

alter table public.section_titles enable row level security;

drop policy if exists "public read section_titles" on public.section_titles;
create policy "public read section_titles" on public.section_titles
  for select using (true);

drop policy if exists "admin write section_titles insert" on public.section_titles;
create policy "admin write section_titles insert" on public.section_titles
  for insert to authenticated with check (public.is_admin());

drop policy if exists "admin write section_titles update" on public.section_titles;
create policy "admin write section_titles update" on public.section_titles
  for update to authenticated using (public.is_admin());

drop policy if exists "admin write section_titles delete" on public.section_titles;
create policy "admin write section_titles delete" on public.section_titles
  for delete to authenticated using (public.is_admin());
