import { useCallback } from "react";
import { useLang } from "@/i18n/LangContext";

/**
 * Terjemahan teks Admin Panel. Kuncinya = teks Indonesia (sama persis dengan
 * yang ada di kode), nilainya = versi English. Kalau bahasa "id" atau kuncinya
 * tidak ada di sini, teks aslinya dipakai — jadi teks baru yang belum
 * diterjemahkan tetap tampil (Indonesia), tidak kosong.
 * Placeholder {nama} diisi lewat argumen kedua tr().
 */
const EN: Record<string, string> = {
  "Memuat": "Loading",
  "Memuat struktur materi": "Loading lesson structure",
  "Memuat…": "Loading…",
  "Tambah Kotoba": "Add Kotoba",
  "Kosakata baru ke database.": "New vocabulary for the database.",
  "Tambah Kanji": "Add Kanji",
  "Karakter kanji baru.": "New kanji characters.",
  "Tambah Bunpō": "Add Bunpō",
  "Pola tata bahasa baru.": "New grammar patterns.",
  "Ringkasan konten yang ada di database Tenka.": "Overview of the content in the Tenka database.",
  "Entri {label}": "{label} Entries",
  "Aksi Cepat": "Quick Actions",
  "Aktivitas Terbaru": "Recent Activity",
  "Belum ada aktivitas. Tambah atau hapus data akan tercatat di sini.": "No activity yet. Adding or deleting data will be logged here.",
  "Menambahkan": "Added",
  "Menghapus": "Deleted",
  "Pilih menu": "Open",
  "di sisi kiri, atau pakai Aksi Cepat di atas, untuk menambah maupun menghapus kosakata, kanji, dan pola tata bahasa.": "in the left sidebar, or use Quick Actions above, to add or delete vocabulary, kanji, and grammar patterns.",
  "Soal": "Questions",
  "Bank soal untuk mode Latihan.": "Question bank for Practice mode.",
  "Pengelolaan bank soal belum tersedia di panel ini.": "Question bank management isn't available in this panel yet.",
  "Statistik": "Statistics",
  "Ringkasan jumlah pengguna dan konten Tenka.": "Overview of Tenka users and content.",
  "Total Pengguna": "Total Users",
  "Total Entri Lessons": "Total Lesson Entries",
  "Rincian Konten per Tier": "Content Breakdown by Tier",
  "Role belum bisa dimuat:": "Couldn't load roles:",
  " — pastikan migrasi 2026_add_user_roles_dev_admin.sql sudah dijalankan.": " — make sure the migration 2026_add_user_roles_dev_admin.sql has been run.",
  "pengguna ini": "this user",
  " Dev punya akses penuh: semua menu Admin Panel, alat dev di app, ubah role, dan hapus akun.": " Dev has full access: all Admin Panel menus, dev tools in the app, changing roles, and deleting accounts.",
  " Admin hanya bisa menambah/mengubah lessons dan latihan.": " Admin can only add/edit lessons and practice.",
  " Akun ini akan kembali jadi pengguna biasa.": " This account will go back to being a regular user.",
  "Ubah {label} menjadi {role}?{warning}": "Change {label} to {role}?{warning}",
  "Menyimpan role…": "Saving role…",
  "Gagal ubah role:": "Failed to change role:",
  "Role {label} sekarang {role}.": "{label}'s role is now {role}.",
  "Hapus akun {label} secara permanen? Tindakan ini tidak bisa dibatalkan.": "Permanently delete {label}'s account? This can't be undone.",
  "Menghapus akun…": "Deleting account…",
  "Gagal hapus akun:": "Failed to delete account:",
  "Akun dihapus.": "Account deleted.",
  "Pengguna": "Users",
  "Daftar pengguna yang terdaftar di Tenka.": "List of users registered on Tenka.",
  "Cari username…": "Search username…",
  "{count} pengguna": "{count} users",
  "Nama": "Name",
  "Bergabung": "Joined",
  "(belum diatur)": "(not set)",
  "Role akun sendiri tidak bisa diubah": "You can't change your own role",
  "Dev bawaan — role dikunci": "Built-in dev — role is locked",
  "Role {name}": "{name}'s role",
  "pengguna": "user",
  "Hapus Akun": "Delete Account",
  "Belum ada pengguna terdaftar.": "No registered users yet.",
  "Tidak ada pengguna yang cocok dengan pencarian.": "No users match your search.",
  "Kembali": "Back",
  "Simpan Perubahan": "Save Changes",
  "Simpan & Tambah Lagi": "Save & Add Another",
  "Simpan": "Save",
  "Batal": "Cancel",
  "Isi nama Organize by (Indonesia atau English).": "Enter an Organize by name (Indonesian or English).",
  "Menyimpan…": "Saving…",
  "Gagal:": "Failed:",
  "tidak diketahui": "unknown",
  "Nama Organize by tidak boleh kosong.": "The Organize by name can't be empty.",
  "Nomor Chapter harus bilangan bulat positif (1, 2, 3…).": "Chapter number must be a positive whole number (1, 2, 3…).",
  "Chapter {n} sudah ada di {source}.": "Chapter {n} already exists in {source}.",
  "Nomor Sub Chapter harus bilangan bulat positif (1, 2, 3…).": "Sub Chapter number must be a positive whole number (1, 2, 3…).",
  "Sub Chapter {sc} sudah ada.": "Sub Chapter {sc} already exists.",
  "Hapus Organize by \"{name}\" di {tier}? {chapters} Chapter dan {entries} {noun} di dalamnya akan terhapus permanen.": "Delete Organize by \"{name}\" in {tier}? {chapters} Chapter(s) and {entries} {noun} inside will be permanently deleted.",
  "Menghapus…": "Deleting…",
  "Gagal hapus:": "Failed to delete:",
  "Organize by \"{name}\" di {tier} dihapus.": "Organize by \"{name}\" in {tier} deleted.",
  "Hapus Chapter {chapter} di {tier} · {source}? Semua Sub Chapter dan {noun} di dalamnya akan terhapus permanen.": "Delete Chapter {chapter} in {tier} · {source}? All Sub Chapters and {noun} inside will be permanently deleted.",
  "Chapter {chapter} di {tier} dihapus.": "Chapter {chapter} in {tier} deleted.",
  "Hapus Sub Chapter {sc} di {tier} · {source}? Semua {noun} di dalamnya akan terhapus permanen.": "Delete Sub Chapter {sc} in {tier} · {source}? All {noun} inside will be permanently deleted.",
  "Sub Chapter {sc} di {tier} dihapus.": "Sub Chapter {sc} in {tier} deleted.",
  "Tutup": "Close",
  "Buka": "Open",
  "Hapus Sub Chapter {label}": "Delete Sub Chapter {label}",
  "Hapus Chapter {n}": "Delete Chapter {n}",
  "Ubah nama Organize by {name}": "Rename Organize by {name}",
  "Hapus Organize by {name}": "Delete Organize by {name}",
  "Tambah Sub Chapter": "Add Sub Chapter",
  "Tambah Chapter": "Add Chapter",
  "Tambah Organize by": "Add Organize by",
  "Hapus Sub Chapter": "Delete Sub Chapter",
  "Bab": "Chapter",
  "Hapus": "Delete",
  "Pilih Sub Chapter di sebelah kiri untuk melihat & mengelola {noun} di dalamnya.": "Select a Sub Chapter on the left to view & manage its {noun}.",
  "Belum ada {noun} di Sub Chapter ini.": "No {noun} in this Sub Chapter yet.",
  "Arti": "Meaning",
  "Cara Baca": "Reading",
  "Pola": "Pattern",
  "Pilih Sub Chapter dulu, lalu klik \"{label}\".": "Select a Sub Chapter first, then click \"{label}\".",
  "Pilih Sub Chapter dulu di daftar sebelum menambah entri.": "Select a Sub Chapter in the list before adding an entry.",
  "Perubahan tersimpan.": "Changes saved.",
  "Tersimpan.": "Saved.",
  "Tersimpan. Silakan tambah entri berikutnya.": "Saved. Go ahead and add the next entry.",
  "Hapus entry ini?": "Delete this entry?",
  "Informasi Utama": "Main Information",
  "Arti Indonesia": "Indonesian Meaning",
  "Arti English": "English Meaning",
  "Contoh Penggunaan": "Usage Example",
  "Contoh kalimat beserta terjemahannya.": "An example sentence with its translation.",
  "Kalimat Jepang": "Japanese Sentence",
  "Kalimat Jepang (Kanji)": "Japanese Sentence (Kanji)",
  "Pisahkan tiap kata dengan / (mis. わたし/は/がくせい/です。). Tanda / cuma buat memisah, tidak ikut tampil di kalimat.": "Separate each word with / (e.g. わたし/は/がくせい/です。). The / is only a separator and doesn't appear in the sentence.",
  "Terjemahan Indonesia": "Indonesian Translation",
  "Terjemahan English": "English Translation",
  "Catatan": "Note",
  "Catatan (ID)…": "Note (ID)…",
  "Catatan (EN)…": "Note (EN)…",
  "Kana (bacaan penuh)": "Kana (full reading)",
  "Pola (Pattern)": "Pattern",
  "Versi Rumpang": "Blank Version",
  "(opsional)": "(optional)",
  "Kelola kosakata yang tersimpan di database Supabase.": "Manage the vocabulary stored in the Supabase database.",
  "Kelola kanji yang tersimpan di database.": "Manage the kanji stored in the database.",
  "Kelola pola tata bahasa yang tersimpan di database.": "Manage the grammar patterns stored in the database.",
  "Tambah Organize by — {tier}": "Add Organize by — {tier}",
  "Ubah Nama Organize by — {tier}": "Rename Organize by — {tier}",
  "Tambah Sub Chapter — {tier} Chapter {chapter}": "Add Sub Chapter — {tier} Chapter {chapter}",
  "Organize by menandai materi di {tier} ini disusun berdasarkan apa — mis. Minna no Nihongo, Genki, atau Tema Harian. Setelah dibuat, isi dengan Chapter dan Sub Chapter.": "Organize by marks what the {tier} material is organized around — e.g. Minna no Nihongo, Genki, or Daily Themes. Once created, fill it with Chapters and Sub Chapters.",
  "Lokasi": "Location",
  "Nomor Chapter": "Chapter Number",
  "Angka bulat, mis. 1, 2, 3.": "Whole number, e.g. 1, 2, 3.",
  "Nomor Sub Chapter": "Sub Chapter Number",
  "Nama (Indonesia)": "Name (Indonesian)",
  "Isi salah satu bahasa, yang kosong ikut bahasa lainnya.": "Fill in either language; the empty one follows the other.",
  "Bebas diisi. Kosongkan untuk pakai nama default.": "Optional. Leave blank to use the default name.",
  "Baru saja": "Just now",
  "{n} menit lalu": "{n} min ago",
  "{n} jam lalu": "{n} h ago",
  "{n} hari lalu": "{n} d ago",
};

export function useAdminTr() {
  const { lang } = useLang();
  const tr = useCallback(
    (id: string, vars?: Record<string, string | number>): string => {
      let s = id;
      if (lang === "en") {
        // "Contoh: xxx" (placeholder contoh isian) → "Example: xxx"
        s = EN[id] ?? (id.startsWith("Contoh: ") ? "Example: " + id.slice(8) : id);
      }
      if (vars) {
        for (const k of Object.keys(vars)) s = s.split(`{${k}}`).join(String(vars[k]));
      }
      return s;
    },
    [lang],
  );
  return { tr, lang };
}
